drop extension if exists "pg_net";


  create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" text not null,
    "last_name" text not null,
    "birth_year" bigint not null,
    "birth_month" bigint default '1'::bigint,
    "birth_day" bigint default '1'::bigint,
    "team_id" bigint not null
      );


alter table "public"."players" enable row level security;


  create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team_name" text not null
      );


alter table "public"."teams" enable row level security;


  create table "public"."test_type" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "test_name" character varying not null,
    "category" integer not null
      );


alter table "public"."test_type" enable row level security;


  create table "public"."tests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seconds" double precision,
    "taken_at" timestamp with time zone not null default now(),
    "player_id" bigint not null,
    "type_id" bigint not null,
    "points" smallint
      );


alter table "public"."tests" enable row level security;

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX test_type_pkey ON public.test_type USING btree (id);

CREATE UNIQUE INDEX tests_pkey ON public.tests USING btree (id);

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."test_type" add constraint "test_type_pkey" PRIMARY KEY using index "test_type_pkey";

alter table "public"."tests" add constraint "tests_pkey" PRIMARY KEY using index "tests_pkey";

alter table "public"."players" add constraint "players_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."players" validate constraint "players_team_id_fkey";

alter table "public"."tests" add constraint "tests_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.players(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tests" validate constraint "tests_player_id_fkey";

alter table "public"."tests" add constraint "tests_type_id_fkey" FOREIGN KEY (type_id) REFERENCES public.test_type(id) ON UPDATE CASCADE not valid;

alter table "public"."tests" validate constraint "tests_type_id_fkey";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."test_type" to "anon";

grant insert on table "public"."test_type" to "anon";

grant references on table "public"."test_type" to "anon";

grant select on table "public"."test_type" to "anon";

grant trigger on table "public"."test_type" to "anon";

grant truncate on table "public"."test_type" to "anon";

grant update on table "public"."test_type" to "anon";

grant delete on table "public"."test_type" to "authenticated";

grant insert on table "public"."test_type" to "authenticated";

grant references on table "public"."test_type" to "authenticated";

grant select on table "public"."test_type" to "authenticated";

grant trigger on table "public"."test_type" to "authenticated";

grant truncate on table "public"."test_type" to "authenticated";

grant update on table "public"."test_type" to "authenticated";

grant delete on table "public"."test_type" to "service_role";

grant insert on table "public"."test_type" to "service_role";

grant references on table "public"."test_type" to "service_role";

grant select on table "public"."test_type" to "service_role";

grant trigger on table "public"."test_type" to "service_role";

grant truncate on table "public"."test_type" to "service_role";

grant update on table "public"."test_type" to "service_role";

grant delete on table "public"."tests" to "anon";

grant insert on table "public"."tests" to "anon";

grant references on table "public"."tests" to "anon";

grant select on table "public"."tests" to "anon";

grant trigger on table "public"."tests" to "anon";

grant truncate on table "public"."tests" to "anon";

grant update on table "public"."tests" to "anon";

grant delete on table "public"."tests" to "authenticated";

grant insert on table "public"."tests" to "authenticated";

grant references on table "public"."tests" to "authenticated";

grant select on table "public"."tests" to "authenticated";

grant trigger on table "public"."tests" to "authenticated";

grant truncate on table "public"."tests" to "authenticated";

grant update on table "public"."tests" to "authenticated";

grant delete on table "public"."tests" to "service_role";

grant insert on table "public"."tests" to "service_role";

grant references on table "public"."tests" to "service_role";

grant select on table "public"."tests" to "service_role";

grant trigger on table "public"."tests" to "service_role";

grant truncate on table "public"."tests" to "service_role";

grant update on table "public"."tests" to "service_role";


  create policy "Allow authenticated add players"
  on "public"."players"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Allow authenticated edit players"
  on "public"."players"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable read access for authenticated users"
  on "public"."players"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."teams"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."test_type"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."tests"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authenticated users"
  on "public"."tests"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow listening for broadcasts for authenticated users only"
  on "realtime"."messages"
  as permissive
  for select
  to authenticated
using ((extension = 'broadcast'::text));



